language: node_js
node_js:
    - "node"

notifications:
    email:
        - xisabla.dev@gmail.com

before_install:
    - npm install --global eslint
    
install:
    - npm install

deploy:
    provider: heroku
    api_key:
        secure: VkavfGqyiIFxeoHXR0WOXm9dt6W50eYIOsHovfEADTZmPmS6STpfwQZJ5m7cbDYXccb8iz9OQZBgRCsIHQBfO4X5SefNHDBkoTz/AtL7xGIg/8vIP3mtpAfSpIqDXYd4iXFiFa5Qt3MpRgiM8T9OTPQk1cSI1OvivN2FSGVECoBkL1Lld9XNpvEzQ2O6fPEFjFZB36FYHJSuFnjupjTHdrv/lVI9QoD1axRaLuFHFMbcl6PVIfVZDDvMLFX78UnGPws6I8+TC+5y0sp7p1zfz5UVUEOa2rBJYgKsBOcSQxRDC/3x1VhoaNwUAD1XA0R/TOGaf19lbKX2CPri3uz350Iv2jWMzUNs7k/crTBgdLZd6a3hDYUC9vh5sCFo1CfnKowm9aIK/UVf9UNBVFEAfu7oC/fo/EOTxBIJViWfY4RgkWqrMMlFNuhQ/pG7Z1d06009uKPCMWUHNFcnKV1ajzg5nvhOvEBXj8LUWrAUOnAXfrfm328vw7WjYeB0f7R6huTg75qqbmcpwIUuHdI9R5S3zG5rt6lo8x/8Eh6iDUrnLMy3NgYBSBHsxTlFk8MfjVkOvwX9ZKaJdSo8qSDVcd0zQU3f+1CxDP9VYfuC/PH6pvQt23o3wYoRiVFAnjktCicdHP/pSxLe5hy3gKbekzIEdrh02rrWj6c21eV56mY=